# Use the official Jupyter base-notebook image from Docker Hub
FROM jupyter/base-notebook:latest

# Set the working directory
WORKDIR /home/jovyan/work

# Start the Jupyter Notebook server
CMD ["start-notebook.sh", "--NotebookApp.token=''", "--NotebookApp.password=''"]
